### ISSUE TITLE
Move API key to environment variable

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/weather-app-api#16]
Move the API key of this project to environment variable.

**Comment by imabhinavagarwal** [comment]
@codemaniac-sahil I would like to take it up. Can you assign this to me?

**Comment by Gathin23** [comment]
Can u assign me this one

**Comment by codemaniac-sahil** [comment]
Yes, @Gathin23

**Comment by Gathin23** [comment]
I have given pull request with the required changes

**Comment by codemaniac-sahil** [comment]
It is unable to fetch the data from API

**Comment by imabhinavagarwal** [comment]
@Gathin23 it will not work. @codemaniac-sahil I was about to comment about the same what @Gathin23  has done.
What he has done is correct but since this is vanilla js, require won't work. And in turn, .env won't work either. 
There can be two approaches to this, either write your own impl of require() or store all env files in another js file and import them as constants in script file which is useless since that will also require pushing your keys to github repo which goes against the whole principle of making env vars.
If you want that solution, I can make the changes right away. or else you can look to move the project to use node js

**Comment by codemaniac-sahil** [comment]
@imabhinavagarwal thank you for your suggestion. Now I am closing this issue.
